// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasinmazBackend.Data;

#nullable disable

namespace TasinmazBackend.Migrations
{
    [DbContext(typeof(TasinmazDbContext))]
    [Migration("20251210072413_InitialCreate_v3")]
    partial class InitialCreate_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TasinmazBackend.Entities.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Iller", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ankara"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "İstanbul"
                        });
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çankaya",
                            IlId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Keçiören",
                            IlId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kadıköy",
                            IlId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Beşiktaş",
                            IlId = 2
                        });
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalleler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kızılay",
                            IlceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Dikmen",
                            IlceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Bağlum",
                            IlceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Moda",
                            IlceId = 3
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Erenköy",
                            IlceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Levent",
                            IlceId = 4
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Akatlar",
                            IlceId = 4
                        });
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Tasinmaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MahalleId")
                        .HasColumnType("int");

                    b.Property<string>("Nitelik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parsel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MahalleId");

                    b.ToTable("Tasinmazlar", (string)null);
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Ilce", b =>
                {
                    b.HasOne("TasinmazBackend.Entities.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Mahalle", b =>
                {
                    b.HasOne("TasinmazBackend.Entities.Ilce", "Ilce")
                        .WithMany("Mahalleler")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Tasinmaz", b =>
                {
                    b.HasOne("TasinmazBackend.Entities.Mahalle", "Mahalle")
                        .WithMany("Tasinmazlar")
                        .HasForeignKey("MahalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mahalle");
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Il", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Ilce", b =>
                {
                    b.Navigation("Mahalleler");
                });

            modelBuilder.Entity("TasinmazBackend.Entities.Mahalle", b =>
                {
                    b.Navigation("Tasinmazlar");
                });
#pragma warning restore 612, 618
        }
    }
}
